---
apiVersion: v1
kind: Secret
metadata:
  name: git-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:biskitsx/argo-cd-private.git
  sshPrivateKey: |
    your private key
  insecue: "false"
  enableLfs: "true" 